import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';

import './globals.css';
import Providers from '@/app/providers';

const manrope = Manrope({
    variable: '--font-manrope',
    subsets: ['latin', 'cyrillic'],
    weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={manrope.variable}>
            <body className="antialiased">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
