import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';

import '@/app/globals.css';
import Providers from '@/app/providers';

import {
    Header,
    // Footer
} from '@/shared/ui';

const manrope = Manrope({
    variable: '--font-manrope',
    subsets: ['latin', 'cyrillic'],
    weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
    title: {
        template: '%s · Диалог',
        default: 'Диалог',
    },
    description: 'Generated by create next app',
};

export default function InnerLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className={manrope.variable}>
            <body className="antialiased">
                <Providers>
                    <Header />
                    {children}
                    {/*<Footer />*/}
                </Providers>
            </body>
        </html>
    );
}
